sudo: required
dist: xenial
language: generic
env:
  matrix: 
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

  global:
  - secure: ZUaYb2lsUb31Oz54glD1ol8Skjw0N/lqI1C7cYmjaiU8HDRAomlbVAW8Mw8IKZr6cNAI1DaD41P45YGG8zu40VFLySdfHblBGed01VkH8G9bHelRTmWS86Si64TwBrFYk5YCKhw8CEQrOmItSqbSmIg9y1Jm37NJR4OroqObzyA7lHHkFxRADoP69dS1esSMgPIS5mkMrvuVd9YpsnEC2Nxja0CtUAlzSj1LTh4H1t5RCOZzgq1+zPZZE64BRFfrWzwfudyJ4Tzrx0mJ1063yAhhbLbkLjheYNK/f0yOCB6bUUGay618Ify9DmAwZk8iQzCFc23H5+3U17vhTP9ohmvdRYb8NfxZ3bDCmCBeJYHg+ImrLABIqZtfCbv2Fwd5gf2ApF7/iYcrTccTJLG/hfDLe8GfQrZ29Led2JDYsjvYNQvsP8fvI0Ag3ldZBo4MZ9NNZeXdxxxg0oU5fvtj8zsFf+r13osdMlwxwZ8U/AyTc1byCX2FSEUBYTXBG8o4MliDB5QIJOKCJ0O8NEcojoe8fYepDxg1KawTUD5mcwTvNrYIbOqEzx8HLFCfdtqyFo2QDQwoPdeNBeVpvAu8amgip5wNJTd7KOSzQGpainDYSdOKu96OQ6h0nEhnFcdUHrqwuuOLKRdP108O1DsGW+KB5eh/qs+nAWOE5rFhk0Q=

install:
- sudo add-apt-repository ppa:gert-die/trusty-mia -y
- sudo add-apt-repository ppa:gert-die/ginkgocadx-trusty -y
- sudo apt-get update -qq
- sudo apt-get install -y libvtk6-dev libinsighttoolkit4-dev libdcmtk-dev libcairo2-dev
  libcurl4-gnutls-dev libfftw3-dev libfreetype6-dev libgtk2.0-dev libjsoncpp-dev libmysqlclient-dev
  libsqlite3-dev libssl-dev libwrap0 libwrap0-dev libwxgtk3.0-dev libxml2-dev libgdcm-tools
  libhdf5-dev
before_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE}  .. 
script:
- make -j2

addons:
  coverity_scan:
    project:
      name: gerddie/ginkgocadx
      version: 3.7.5+
      description: 
    notification_email: gw.fossdev@gmail.com
    build_command: make -j2
    branch_pattern: coverity_scan

